tree_name: Events
dilepton_MC:
- DYJetsToLL_M-50_HT-70to100
- DYJetsToLL_M-50_HT-100to200
- DYJetsToLL_M-50_HT-200to400
- DYJetsToLL_M-50_HT-400to600
- DYJetsToLL_M-50_HT-600to800
- DYJetsToLL_M-50_HT-800to1200
- DYJetsToLL_M-50_HT-1200to2500
- DYJetsToLL_M-50_HT-2500toInf
photon_MC: 
- GJets_HT-40To100
- GJets_HT-100To200
- GJets_HT-200To400
- GJets_HT-400To600
- GJets_HT-600ToInf
file_paths:
  GJets_HT-40To100: /eos/cms/store/user/mmittal/VBS/PhotonCR2016_09092021/GJets_HT-40To100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  GJets_HT-100To200: /eos/cms/store/user/mmittal/VBS/PhotonCR2016_09092021/GJets_HT-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  GJets_HT-200To400: /eos/cms/store/user/mmittal/VBS/PhotonCR2016_09092021/GJets_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  GJets_HT-400To600: /eos/cms/store/user/mmittal/VBS/PhotonCR2016_09092021/GJets_HT-400To600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  GJets_HT-600ToInf: /eos/cms/store/user/mmittal/VBS/PhotonCR2016_09092021/GJets_HT-600ToInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  DYJetsToLL_M-50_HT-70to100: /eos/cms/store/group/phys_smp/ZZTo2L2Nu/VBS/SGP2016/DYJetsToLL_M-50_HT-70to100_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  DYJetsToLL_M-50_HT-100to200: /eos/cms/store/group/phys_smp/ZZTo2L2Nu/VBS/SGP2016/DYJetsToLL_M-50_HT-100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  DYJetsToLL_M-50_HT-200to400: /eos/cms/store/group/phys_smp/ZZTo2L2Nu/VBS/SGP2016/DYJetsToLL_M-50_HT-200to400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  DYJetsToLL_M-50_HT-400to600: /eos/cms/store/group/phys_smp/ZZTo2L2Nu/VBS/SGP2016/DYJetsToLL_M-50_HT-400to600_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  DYJetsToLL_M-50_HT-600to800: /eos/cms/store/group/phys_smp/ZZTo2L2Nu/VBS/SGP2016/DYJetsToLL_M-50_HT-600to800_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  DYJetsToLL_M-50_HT-800to1200: /eos/cms/store/group/phys_smp/ZZTo2L2Nu/VBS/SGP2016/DYJetsToLL_M-50_HT-800to1200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  DYJetsToLL_M-50_HT-1200to2500: /eos/cms/store/group/phys_smp/ZZTo2L2Nu/VBS/SGP2016/DYJetsToLL_M-50_HT-1200to2500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
  DYJetsToLL_M-50_HT-2500toInf: /eos/cms/store/group/phys_smp/ZZTo2L2Nu/VBS/SGP2016/DYJetsToLL_M-50_HT-2500toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8
isMC: true
lumi: 35900
xsec:
  GJets_HT-40To100: 20790.0 
  GJets_HT-100To200: 9197.0
  GJets_HT-200To400: 2317.0
  GJets_HT-400To600: 276.9
  GJets_HT-600ToInf: 94.28
  DYJetsToLL_M-50_HT-70to100: 169.9
  DYJetsToLL_M-50_HT-100to200: 147.40
  DYJetsToLL_M-50_HT-200to400: 40.99
  DYJetsToLL_M-50_HT-400to600: 5.678
  DYJetsToLL_M-50_HT-600to800: 1.367
  DYJetsToLL_M-50_HT-800to1200: 0.6304
  DYJetsToLL_M-50_HT-1200to2500: 0.1514
  DYJetsToLL_M-50_HT-2500toInf: 0.003565
   
