tree_name: Events
lumi: 1.0
samples:
  - DY
  - GJets
types:
  DY: dilepton_MC
  GJets: photon_MC
file_paths:
  DY: samples/DY
  GJets: samples/Gjet
xsec:
  DY: 1
  GJets: 1
attributes:
  DY:
    type: dilepton_MC
    xsec: 1.0
    path: samples/DY
    process: DY
  GJets:
    type: photon_MC
    xsec: 1.0
    path: samples/Gjet
    process: GJets
branch:
  common:
  - nJet
  - Jet_pt_nom
  - lead_jet_pt
  - lead_jet_phi
  - trail_jet_pt
  - trail_jet_eta
  - trail_jet_phi
  - lep_category
  - ngood_jets
  - ngood_bjets
  - nhad_taus
  - met_pt
  - met_phi
  - delta_R_ll
  - delta_phi_j_met
  - Jet_etas_multiplied
  - dijet_Mjj
  - dijet_abs_dEta
  - Z_pt
  - Z_eta
  - Z_phi
  - Z_mass
  - Pileup_nPU
  - delta_phi_ZMet
  photon:
  - nPhoton
  - nMuon
  - nElectron
  - ngood_leptons
  - nextra_leptons
  MC:
  - weight
HLT:
  dilepton_MC:
  - HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL  # Unprescaled in run <= 280385
  - HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ
  - HLT_IsoMu24
  - HLT_Mu50
  - HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
  - HLT_DoubleEle33_CaloIdL_MW  # Unprescaled in run <= 276437 and run >= 278873
  - HLT_Ele27_WPTight_Gsf
  photon_MC:
  - HLT_Photon50_R9Id90_HE10_IsoM
  - HLT_Photon75_R9Id90_HE10_IsoM
  - HLT_Photon90_R9Id90_HE10_IsoM
  - HLT_Photon120_R9Id90_HE10_IsoM
  - HLT_Photon165_R9Id90_HE10_IsoM
  - HLT_Photon175
